### ISSUE TITLE
检查valueLen合法性 是不是 bodyLen != buffer.Cap()-d.headerLen 更好些

### ISSUE THREAD

**Issue by exuan** [alberliu/gn#2]
rt,
另外 `bodyLen==0` 这个情况 也处理， 虽然后面 `proto.Unmarshal` 也能抛出错误

https://github.com/alberliu/gn/blob/7649abd937a6ce9e1a2fd69d8146aeace6a2034b/codec.go#L47

**Comment by alberliu** [comment]
bodyLen > buffer.Cap()-d.headerLen，
这样写是不对的，bodylen <= buffer.Cap()-d.headerLen,两个之间没有等于关系

**Comment by alberliu** [comment]
bodyLen==0，这个是合理的，后面会加上去
